export const collections = [
  {
    id: "STRA-f777be",
    name: "The Strangers",
    imgUrl: "/assets/img/collections/STRA-f777be.png",
    rank: 0,
  },
  {
    id: "GUARDIAN-3d6635",
    name: "Aquaverse",
    imgUrl: "/assets/img/collections/GUARDIAN-3d6635.png",
    quantity: 9999,
    min: 1,
    max: 9999,
    rank: 1,
  },
  {
    id: "DRIFTERS-efd96c",
    name: "Drifters",
    imgUrl: "/assets/img/collections/DRIFTERS-efd96c.png",
    quantity: 10000,
    min: 0,
    max: 9999,
    rank: 2,
  },
  {
    id: "DAPEZ-c88658",
    name: "DaApez",
    imgUrl: "/assets/img/collections/DAPEZ-c88658.png",
    quantity: 5555,
    min: 1,
    max: 5555,
    rank: 3,
  },
  {
    id: "GNOGONS-73222b",
    name: "Gnogons",
    imgUrl: "/assets/img/collections/GNOGONS-73222b.png",
    rank: 4,
  },
  /*{
        id: "MAIARPUNKS-3db7e8",
        name: "MaiarPunks",
        imgUrl: "/assets/img/collections/MAIARPUNKS-3db7e8.png",
        rank: 6
    },*/
  {
    id: "OAG-0eaf3b",
    name: "Odd Apes Gang",
    imgUrl: "/assets/img/collections/OAG-0eaf3b.png",
    rank: 7,
  },
  {
    id: "HSWOLF-76e8bf",
    name: "High Street Wolf Society",
    imgUrl: "/assets/img/collections/HSWOLF-76e8bf.png",
    rank: 7,
  },
  {
    id: "PIGLETHH-7357ca",
    name: "Piglet Homies",
    imgUrl: "/assets/img/collections/PIGLETHH-7357ca.png",
    rank: 8,
  },
  {
    id: "APC-928458",
    name: "Angry Penguins Colony",
    imgUrl: "/assets/img/collections/APC-928458.png",
    rank: 9,
  },
  {
    id: "BDGA-a05446",
    name: "Babies Degen Ape",
    imgUrl: "/assets/img/collections/BDGA-a05446.png",
    rank: 9,
  },
  {
    id: "MANY-39af2c",
    name: "The Faceless Many",
    imgUrl: "/assets/img/collections/MANY-39af2c.png",
    rank: 9,
  },
  {
    id: "QUACK-f01e02",
    name: "Elrond Ducks",
    imgUrl: "/assets/img/collections/QUACK-f01e02.png",
    rank: 9,
  },
  {
    id: "SAC-c60db0",
    name: "Salvadorian Ape Club",
    imgUrl: "/assets/img/collections/SAC-c60db0.png",
    rank: 10,
  },
  {
    id: "WWWINE-5a5331",
    name: "Wwwine",
    imgUrl: "/assets/img/collections/WWWINE-5a5331.png",
    rank: 10,
  },
  {
    id: "WARRIORZ-2f0986",
    name: "Elrond Warriorz",
    imgUrl: "/assets/img/collections/WARRIORZ-2f0986.png",
    rank: 10,
  },
  {
    id: "PITTZ-1a4c2d",
    name: "CryptoPittz",
    imgUrl: "/assets/img/collections/PITTZ-1a4c2d.png",
    rank: 10,
  },
  /*{
    id: "TOC-eea288",
    name: "Tigers On Chain",
    imgUrl: "/assets/img/collections/TOC-eea288.png",
    rank: 11,
  },*/
  {
    id: "KROGAN-54c361",
    name: "Krogan",
    imgUrl: "/assets/img/collections/KROGAN-54c361.png",
    rank: 11,
  },
];
